<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../src/AlertaRio.Api/AlertaRio.Api.csproj" />
    <ProjectReference Include="../../src/AlertaRio.Core/AlertaRio.Core.csproj" />
    <ProjectReference Include="../../src/AlertaRio.Worker/AlertaRio.Worker.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../../contracts/openapi/v1.json" Link="v1.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
